# -*- coding: utf-8 -*-
"""XGBModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPMCr3Z8LU_HV2j2fLUuvBPyUSeWsYBL
"""

# --- XGBoost Model ---
xgb_model_high = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)
xgb_model_low = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

xgb_model_high.fit(X_train, y_high_train)
xgb_model_low.fit(X_train, y_low_train)

# --- Evaluation ---
y_high_pred_lr = lr_model_high.predict(X_test)
y_low_pred_lr = lr_model_low.predict(X_test)

y_high_pred_xgb = xgb_model_high.predict(X_test)
y_low_pred_xgb = xgb_model_low.predict(X_test)

# Evaluation Metrics
mse_high_lr = mean_squared_error(y_high_test, y_high_pred_lr)
mae_high_lr = mean_absolute_error(y_high_test, y_high_pred_lr)
r2_high_lr = r2_score(y_high_test, y_high_pred_lr)

mse_low_lr = mean_squared_error(y_low_test, y_low_pred_lr)
mae_low_lr = mean_absolute_error(y_low_test, y_low_pred_lr)
r2_low_lr = r2_score(y_low_test, y_low_pred_lr)

mse_high_xgb = mean_squared_error(y_high_test, y_high_pred_xgb)
mae_high_xgb = mean_absolute_error(y_high_test, y_high_pred_xgb)
r2_high_xgb = r2_score(y_high_test, y_high_pred_xgb)

mse_low_xgb = mean_squared_error(y_low_test, y_low_pred_xgb)
mae_low_xgb = mean_absolute_error(y_low_test, y_low_pred_xgb)
r2_low_xgb = r2_score(y_low_test, y_low_pred_xgb)

print("Linear Regression Model - High Price Prediction:")
print(f"MSE: {mse_high_lr}, MAE: {mae_high_lr}, R²: {r2_high_lr}")
print("\nLinear Regression Model - Low Price Prediction:")
print(f"MSE: {mse_low_lr}, MAE: {mae_low_lr}, R²: {r2_low_lr}")
print("\nXGBoost Model - High Price Prediction:")
print(f"MSE: {mse_high_xgb}, MAE: {mae_high_xgb}, R²: {r2_high_xgb}")
print("\nXGBoost Model - Low Price Prediction:")
print(f"MSE: {mse_low_xgb}, MAE: {mae_low_xgb}, R²: {r2_low_xgb}")